import {randomUUID} from 'node:crypto';
import {type Store,type Queryable,one} from './database.ts';
import {DomainError,Vault,fingerprint,centsToAtomic,uiUnits} from './security.ts';
import {type PaymentProvider,validateReceipt,type DepositClaim} from './providers.ts';
export type Identity={id:string;email:string;name:string;aal?:string;source?:'supabase'|'sites';ip?:string;userAgent?:string};
export type Actor=Identity & {role:string|null;permissions:string[];requireMfa:boolean};
const requirePermission=(a:Actor,p:string)=>{if(!a.permissions.includes(p))throw new DomainError('Permission required: '+p,403);};
const openWithdrawal=['REQUESTED','UNDER_REVIEW','PROCESSING'];
export class WalletDomain{
 constructor(readonly db:Store,readonly vault:Pick<Vault,'encrypt'|'decrypt'>,readonly provider:PaymentProvider,readonly mode:'test'|'provider'='test',readonly tokenContract='TEST-USDT',readonly confirmations=20){if(!Number.isSafeInteger(confirmations)||confirmations<1)throw new Error('REQUIRED_CONFIRMATIONS must be a positive integer.');}
 async actor(identity:Identity):Promise<Actor>{
  await this.db.transaction(async q=>{
   await q.query('INSERT INTO users(id,email,name) VALUES($1,$2,$3) ON CONFLICT(id) DO NOTHING',[identity.id,identity.email,identity.name]);
   await q.query('INSERT INTO profiles(user_id) VALUES($1) ON CONFLICT DO NOTHING',[identity.id]);
   await q.query('INSERT INTO wallets(user_id) VALUES($1) ON CONFLICT DO NOTHING',[identity.id]);
   await q.query('INSERT INTO referral_codes(user_id,code) VALUES($1,$2) ON CONFLICT DO NOTHING',[identity.id,'NILA-'+fingerprint(identity.id).slice(0,12).toUpperCase()]);
   if(this.mode==='test')await q.query("INSERT INTO deposit_addresses(user_id,asset,network,address) VALUES($1,'USDT','TRC20',$2) ON CONFLICT DO NOTHING",[identity.id,'TEST-NILA-'+fingerprint(identity.id).slice(0,24)]);
  });
  const u=await one(this.db,'SELECT u.*,a.role_id,a.require_mfa FROM users u LEFT JOIN admin_users a ON a.user_id=u.id AND a.enabled WHERE u.id=$1',[identity.id]);
  const p=u.role_id&&u.status==='Active'?(await this.db.query('SELECT permission_id FROM admin_role_permissions WHERE role_id=$1',[u.role_id])).rows.map(r=>r.permission_id):[];
  return {...identity,name:u.name,role:u.status==='Active'?u.role_id||null:null,permissions:p,requireMfa:u.require_mfa??false};
 }
 async administrator(identity:Identity){const a=await this.actor(identity);if(!a.role)throw new DomainError('Administrator authentication required.',403);if(a.aal!=='aal2')throw new DomainError('An MFA-verified Supabase session is required for this administrator.',403);return a;}
 async active(q:Queryable,userId:string){const u=await one(q,'SELECT * FROM users WHERE id=$1 FOR SHARE',[userId]);if(!u||u.status!=='Active')throw new DomainError('The account is suspended.',403);return u;}
 async clearSecurity(q:Queryable,userId:string){if(await one(q,"SELECT id FROM security_events WHERE user_id=$1 AND status='Open' LIMIT 1",[userId]))throw new DomainError('Resolve the account security review first.',409);}
 async lockWallet(q:Queryable,userId:string){const w=await one(q,'SELECT * FROM wallets WHERE user_id=$1 FOR UPDATE',[userId]);if(!w)throw new DomainError('Wallet not found.',404);return w;}
 async balance(q:Queryable,walletId:string){const b=await one(q,"SELECT COALESCE((SELECT sum(amount_atomic) FROM wallet_ledger WHERE wallet_id=$1),0)::text total,COALESCE((SELECT sum(amount_atomic) FROM wallet_holds WHERE wallet_id=$1 AND status='ACTIVE'),0)::text held",[walletId]);return {total:BigInt(b.total),held:BigInt(b.held),available:BigInt(b.total)-BigInt(b.held)};}
 async audit(q:Queryable,a:Actor,action:string,type:string,id:string,reason:string,before:unknown,after:unknown){if(reason.trim().length<5)throw new DomainError('A reason of at least five characters is required.');await q.query('INSERT INTO audit_logs(admin_user_id,action,resource_type,resource_id,reason,previous_state,new_state,ip_address,user_agent) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[a.id,action,type,id,reason,before?JSON.stringify(before):null,after?JSON.stringify(after):null,a.ip||null,a.userAgent?.slice(0,500)||null]);}
 async event(q:Queryable,userId:string,kind:string,id:string){await q.query('INSERT INTO domain_events(user_id,kind,resource_id) VALUES($1,$2,$3)',[userId,kind,id]);}
 async notify(q:Queryable,userId:string,key:string){const n=await one(q,'INSERT INTO notifications(user_id,template_id,title,message) SELECT $1,id,title,message FROM notification_templates WHERE id=$2 AND enabled RETURNING id',[userId,key]);if(n)await q.query("INSERT INTO notification_outbox(notification_id,connection_id) SELECT $1,c.id FROM notification_connections c JOIN notification_templates t ON t.id=$3 WHERE c.user_id=$2 AND c.revoked_at IS NULL AND t.channels ? c.channel ON CONFLICT DO NOTHING",[n.id,userId,key]);}
 async atomic(a:Actor,key:string,payload:unknown,work:(q:Queryable)=>Promise<unknown>){return this.db.transaction(async q=>{
  const hash=fingerprint(payload);
  const inserted=await one(q,'INSERT INTO idempotency_keys(actor_id,operation_id,request_hash) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING operation_id',[a.id,key,hash]);
  if(!inserted){const old=await one(q,'SELECT * FROM idempotency_keys WHERE actor_id=$1 AND operation_id=$2 FOR UPDATE',[a.id,key]);if(old.request_hash!==hash)throw new DomainError('Idempotency key reused with different input.',409);return old.response;}
  const response=await work(q);await q.query('UPDATE idempotency_keys SET response=$3 WHERE actor_id=$1 AND operation_id=$2',[a.id,key,JSON.stringify(response??{ok:true})]);return response??{ok:true};
 });}
 async replay(a:Actor,c:any){const old=await one(this.db,'SELECT request_hash,response FROM idempotency_keys WHERE actor_id=$1 AND operation_id=$2',[a.id,c.operationId]);if(!old)return undefined;if(old.request_hash!==fingerprint(c))throw new DomainError('Idempotency key reused with different input.',409);return old.response;}
 async config(q:Queryable=this.db){return (await one(q,'SELECT * FROM system_settings WHERE id=1'));}
 async settings(a:Actor,c:any){requirePermission(a,'settings.manage');return this.atomic(a,c.operationId,c,async q=>{const old=await one(q,'SELECT * FROM system_settings WHERE id=1 FOR UPDATE');if(old.revision!==c.revision)throw new DomainError('Settings changed. Refresh before saving.',409);await q.query('UPDATE system_settings SET value=$1,revision=revision+1 WHERE id=1',[JSON.stringify(c.settings)]);await q.query('UPDATE referral_settings SET enabled=$1,reward_rate=$2,maximum_reward_atomic=$3,qualification_atomic=$4,revision=revision+1 WHERE id=1',[c.settings.referralsEnabled,c.settings.referralReward/100,String(BigInt(c.settings.referralReward)*10000n),String(BigInt(c.settings.referralMinimum)*10000n)]);await this.audit(q,a,'SYSTEM_SETTING_CHANGED','settings','1',c.reason,old.value,c.settings);return {ok:true};});}
 async submit(a:Actor,c:any){return this.atomic(a,c.operationId,c,async q=>{
  await this.active(q,a.id);await this.clearSecurity(q,a.id);const s=(await this.config(q)).value;const withdrawal=c.type==='Withdrawal';
  if(s.maintenanceMode||!(withdrawal?s.withdrawalsEnabled:s.depositsEnabled))throw new DomainError('These requests are currently paused.');
  const amount=centsToAtomic(c.units);if(c.units<(withdrawal?s.minWithdrawal:s.minDeposit)||c.units>(withdrawal?s.maxWithdrawal:100000000))throw new DomainError('Amount is outside configured limits.');
  const w=await this.lockWallet(q,a.id);let r;
  if(withdrawal){if(c.expectedFee!==s.withdrawalFee)throw new DomainError('The withdrawal fee changed.',409);const m=await one(q,"SELECT * FROM payout_methods WHERE id=$1 AND user_id=$2 AND status='Active' FOR SHARE",[c.methodId,a.id]);if(!m)throw new DomainError('Choose an active payout method.');const fee=BigInt(s.withdrawalFee)*10000n;if((await this.balance(q,w.id)).available<amount+fee)throw new DomainError('Insufficient available funds.',409);
   r=await one(q,'INSERT INTO withdrawal_requests(user_id,wallet_id,payout_method_id,amount_atomic,fee_atomic) VALUES($1,$2,$3,$4,$5) RETURNING *',[a.id,w.id,m.id,String(amount),String(fee)]);
   await q.query('INSERT INTO wallet_holds(wallet_id,withdrawal_id,amount_atomic) VALUES($1,$2,$3)',[w.id,r.id,String(amount+fee)]);await this.notify(q,a.id,'WITHDRAWAL_RECEIVED');
  }else{const address=await one(q,"SELECT * FROM deposit_addresses WHERE user_id=$1 AND active AND asset='USDT' AND network='TRC20' LIMIT 1",[a.id]);if(!address)throw new DomainError('No deposit address is configured for this account.',409);if(this.mode==='provider'&&!/^[a-f0-9]{64}$/i.test(c.reference||''))throw new DomainError('A valid TRON transaction hash is required.');
   r=await one(q,'INSERT INTO deposit_requests(user_id,wallet_id,address_id,amount_atomic,tx_hash) VALUES($1,$2,$3,$4,$5) RETURNING *',[a.id,w.id,address.id,String(amount),(c.reference||'').toLowerCase()]);await this.notify(q,a.id,'DEPOSIT_RECEIVED');}
  await this.audit(q,a,withdrawal?'WITHDRAWAL_REQUESTED':'DEPOSIT_SUBMITTED',withdrawal?'withdrawal':'deposit',r.id,'Submitted by wallet owner',null,{amountAtomic:String(amount),status:r.status});await this.event(q,a.id,'request.created',r.id);return {id:r.id,status:r.status};
 });}
 async stage(a:Actor,c:any){return this.atomic(a,c.operationId,c,async q=>{const deposit=c.stage==='VERIFYING';requirePermission(a,deposit?'deposits.review':'withdrawals.review');const table=deposit?'deposit_requests':'withdrawal_requests';const r=await one(q,`SELECT * FROM ${table} WHERE id=$1 FOR UPDATE`,[c.id]);if(!r)throw new DomainError('Request not found.',404);await this.active(q,r.user_id);await this.clearSecurity(q,r.user_id);const next:Record<string,string>={SUBMITTED:'VERIFYING',REQUESTED:'UNDER_REVIEW',UNDER_REVIEW:'PROCESSING'};if(next[r.status]!==c.stage)throw new DomainError('Invalid request transition.',409);await q.query(`UPDATE ${table} SET status=$2,reviewed_by=$3,reason=$4 WHERE id=$1`,[r.id,c.stage,a.id,c.reason]);await this.audit(q,a,'REQUEST_STAGE_CHANGED',table,r.id,c.reason,{status:r.status},{status:c.stage});await this.event(q,r.user_id,'request.updated',r.id);return {id:r.id,status:c.stage};});}
 async verifyDeposit(a:Actor,c:any){requirePermission(a,'deposits.review');const replay=await this.replay(a,c);if(replay!==undefined)return replay;const current=await one(this.db,'SELECT d.*,a.address FROM deposit_requests d JOIN deposit_addresses a ON a.id=d.address_id WHERE d.id=$1',[c.id]);if(!current)throw new DomainError('Deposit not found.',404);
  const claim:DepositClaim={id:current.id,txHash:current.tx_hash,destination:current.address,amountAtomic:String(current.amount_atomic),asset:'USDT',network:'TRC20'};
  // No checkbox or uploaded image participates in verification.
  const receipt=await this.provider.verify(claim);validateReceipt(claim,receipt,this.tokenContract,this.confirmations,this.mode);
  return this.atomic(a,c.operationId,c,async q=>{const d=await one(q,'SELECT * FROM deposit_requests WHERE id=$1 FOR UPDATE',[c.id]);if(d.status!=='VERIFYING')throw new DomainError('Start verification before confirming this deposit.',409);await this.active(q,d.user_id);await this.clearSecurity(q,d.user_id);await this.lockWallet(q,d.user_id);
   await q.query('INSERT INTO deposit_verifications(deposit_id,provider,evidence) VALUES($1,$2,$3)',[d.id,receipt.provider,JSON.stringify(receipt)]);
   await q.query("INSERT INTO wallet_ledger(wallet_id,amount_atomic,kind,reference,operation_id,request_id,reason,actor_id) VALUES($1,$2,'DEPOSIT_CREDIT',$3,$4,$5,$6,$7)",[d.wallet_id,d.amount_atomic,d.tx_hash,c.operationId,d.id,c.reason,a.id]);
   await q.query("UPDATE deposit_requests SET status='CONFIRMED',reviewed_by=$2,reason=$3,resolved_at=now() WHERE id=$1",[d.id,a.id,c.reason]);
   await q.query("UPDATE referrals SET status='Eligible' WHERE referred_id=$1 AND status='Awaiting deposit' AND (SELECT COALESCE(sum(amount_atomic),0) FROM deposit_requests WHERE user_id=$1 AND status='CONFIRMED') >= (settings_snapshot->>'qualification_atomic')::bigint",[d.user_id]);
   await this.audit(q,a,'DEPOSIT_CONFIRMED','deposit',d.id,c.reason,{status:d.status},{status:'CONFIRMED',receipt});await this.notify(q,d.user_id,'DEPOSIT_CONFIRMED');await this.event(q,d.user_id,'wallet.updated',d.id);return {id:d.id,status:'CONFIRMED'};
  });
 }
 async resolveWithdrawal(a:Actor,c:any){const cancel=c.decision==='cancel';if(!cancel)requirePermission(a,'withdrawals.review');
  return this.atomic(a,c.operationId,c,async q=>{const r=await one(q,'SELECT * FROM withdrawal_requests WHERE id=$1 FOR UPDATE',[c.id]);if(!r||cancel&&r.user_id!==a.id)throw new DomainError('Withdrawal not found.',404);if(!openWithdrawal.includes(r.status)||r.status==='PROCESSING')throw new DomainError('Processing payouts cannot be cancelled or released until the provider confirms failure.',409);await this.lockWallet(q,r.user_id);const status=cancel?'CANCELLED':'REJECTED';
   await q.query("UPDATE wallet_holds SET status='RELEASED',resolved_at=now() WHERE withdrawal_id=$1 AND status='ACTIVE'",[r.id]);await q.query('UPDATE withdrawal_requests SET status=$2,reason=$3,reviewed_by=$4,resolved_at=now() WHERE id=$1',[r.id,status,c.reason,a.id]);await this.audit(q,a,'WITHDRAWAL_'+status,'withdrawal',r.id,c.reason,{status:r.status},{status});await this.notify(q,r.user_id,'WITHDRAWAL_REJECTED');await this.event(q,r.user_id,'wallet.updated',r.id);return {id:r.id,status};
  });
 }
 async payout(a:Actor,c:any){requirePermission(a,'withdrawals.review');const replay=await this.replay(a,c);if(replay!==undefined)return replay;
  // The provider must durably honor this request ID as its idempotency key.
  // The database remains authoritative; an uncertain timeout keeps the hold.
  const r=await one(this.db,'SELECT r.*,p.encrypted_details,p.masked_detail,p.status method_status FROM withdrawal_requests r JOIN payout_methods p ON p.id=r.payout_method_id WHERE r.id=$1',[c.id]);if(!r||r.status!=='PROCESSING')throw new DomainError('Move the withdrawal to processing first.',409);await this.active(this.db,r.user_id);await this.clearSecurity(this.db,r.user_id);if(r.method_status!=='Active')throw new DomainError('Payout method is disabled.',409);
  const destination=this.vault.decrypt(r.encrypted_details,r.user_id);destination.fingerprint=fingerprint(destination);
  await this.db.transaction(q=>this.audit(q,a,'PAYOUT_DATA_ACCESSED','payout_method',r.payout_method_id,c.reason,null,{purpose:'provider_processing'}));
  const receipt=r.provider_reference?await this.provider.receipt(r.provider_reference):await this.provider.payout(r.id,String(r.amount_atomic),destination);
  if(!receipt||!['PROCESSING','COMPLETED','FAILED'].includes(receipt.status)||receipt.amountAtomic!==String(r.amount_atomic)||receipt.destinationFingerprint!==destination.fingerprint||typeof receipt.reference!=='string')throw new DomainError('Provider result could not be matched. Hold retained.',409);
  return this.atomic(a,c.operationId,c,async q=>{const current=await one(q,'SELECT * FROM withdrawal_requests WHERE id=$1 FOR UPDATE',[r.id]);if(current.status!=='PROCESSING')throw new DomainError('This payout already has a final result.',409);await this.lockWallet(q,r.user_id);const status=receipt.status;
   if(status==='COMPLETED'){await q.query("UPDATE wallet_holds SET status='CONSUMED',resolved_at=now() WHERE withdrawal_id=$1 AND status='ACTIVE'",[r.id]);await q.query("INSERT INTO wallet_ledger(wallet_id,amount_atomic,kind,reference,operation_id,request_id,reason,actor_id) VALUES($1,$2,'WITHDRAWAL_DEBIT',$3,$4,$5,$6,$7)",[r.wallet_id,String(-BigInt(r.amount_atomic)-BigInt(r.fee_atomic)),receipt.reference,c.operationId,r.id,c.reason,a.id]);}
   if(status==='FAILED')await q.query("UPDATE wallet_holds SET status='RELEASED',resolved_at=now() WHERE withdrawal_id=$1 AND status='ACTIVE'",[r.id]);
   await q.query("UPDATE withdrawal_requests SET status=$2,provider_reference=$3,reason=$4,reviewed_by=$5,resolved_at=CASE WHEN $2='PROCESSING' THEN NULL ELSE now() END WHERE id=$1",[r.id,status,receipt.reference,c.reason,a.id]);await this.audit(q,a,'WITHDRAWAL_'+status,'withdrawal',r.id,c.reason,{status:'PROCESSING'},{status,providerReference:receipt.reference});if(status!=='PROCESSING')await this.notify(q,r.user_id,status==='COMPLETED'?'WITHDRAWAL_COMPLETED':'WITHDRAWAL_REJECTED');await this.event(q,r.user_id,'wallet.updated',r.id);return {id:r.id,status};
  });
 }
 async rejectDeposit(a:Actor,c:any){requirePermission(a,'deposits.review');return this.atomic(a,c.operationId,c,async q=>{const d=await one(q,'SELECT * FROM deposit_requests WHERE id=$1 FOR UPDATE',[c.id]);if(!d||!['SUBMITTED','VERIFYING'].includes(d.status))throw new DomainError('Deposit already resolved.',409);await q.query("UPDATE deposit_requests SET status='REJECTED',reason=$2,reviewed_by=$3,resolved_at=now() WHERE id=$1",[d.id,c.reason,a.id]);await this.audit(q,a,'DEPOSIT_REJECTED','deposit',d.id,c.reason,{status:d.status},{status:'REJECTED'});await this.notify(q,d.user_id,'DEPOSIT_REJECTED');await this.event(q,d.user_id,'request.updated',d.id);return {id:d.id,status:'REJECTED'};});}
 async adjustment(a:Actor,c:any){requirePermission(a,'ledger.adjust');return this.atomic(a,c.operationId,c,async q=>{await this.active(q,c.userId);const w=await this.lockWallet(q,c.userId);const before=await this.balance(q,w.id);let delta=centsToAtomic(c.units)*(c.direction==='debit'?-1n:1n),reversal=null;
  if(c.adjustmentType==='REVERSAL'){const original=await one(q,'SELECT * FROM wallet_ledger WHERE id=$1 AND wallet_id=$2',[c.reference,w.id]);if(!original)throw new DomainError('Original entry not found.');delta=-BigInt(original.amount_atomic);reversal=original.id;}
  if(before.available+delta<0n)throw new DomainError('Adjustment exceeds available funds.',409);
  const entry=await one(q,'INSERT INTO wallet_ledger(wallet_id,amount_atomic,kind,reference,operation_id,reversal_of,reason,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[w.id,String(delta),c.adjustmentType|| (delta>0n?'CREDIT_ADJUSTMENT':'DEBIT_ADJUSTMENT'),c.reference||c.operationId,c.operationId,reversal,c.reason,a.id]);await this.audit(q,a,'WALLET_ADJUSTMENT_CREATED','wallet',w.id,c.reason,{availableAtomic:String(before.available)},{ledgerId:entry.id,deltaAtomic:String(delta),availableAtomic:String(before.available+delta)});await this.event(q,c.userId,'wallet.updated',entry.id);return entry;
 });}
 async manage(a:Actor,c:any){const permissions:Record<string,string>={user_status:'users.manage',role:'admins.manage',method_status:'payouts.manage',security_review:'security.manage',security_resolve:'security.manage',template:'notifications.manage',notify:'notifications.manage',referral_reward:'referrals.reward',referral_settings:'settings.manage',payout_reveal:'payouts.reveal'};requirePermission(a,permissions[c.action]||'__denied__');return this.atomic(a,c.operationId,c,async q=>{
  let before:any=null,after:any=null,target=c.userId||c.id||'1',userId=c.userId||a.id;
  if(c.action==='user_status'){before=await one(q,'SELECT * FROM users WHERE id=$1 FOR UPDATE',[c.userId]);if(!before)throw new DomainError('User not found.',404);const admin=await one(q,'SELECT role_id FROM admin_users WHERE user_id=$1',[c.userId]);if(c.userId===a.id||admin?.role_id==='SUPER_ADMIN')throw new DomainError('The super administrator account is protected.',403);await q.query('UPDATE users SET status=$2 WHERE id=$1',[c.userId,c.status]);after={status:c.status};}
  if(c.action==='role'){if(c.userId===a.id)throw new DomainError('You cannot change your own administrator role.',403);await this.active(q,c.userId);before=await one(q,'SELECT * FROM admin_users WHERE user_id=$1 FOR UPDATE',[c.userId]);if(before?.role_id==='SUPER_ADMIN')throw new DomainError('Super administrator changes require an operator migration.',403);if(c.role==='none')await q.query('UPDATE admin_users SET enabled=false WHERE user_id=$1',[c.userId]);else await q.query('INSERT INTO admin_users(user_id,role_id,require_mfa) VALUES($1,$2,true) ON CONFLICT(user_id) DO UPDATE SET role_id=excluded.role_id,enabled=true,require_mfa=true',[c.userId,c.role]);after={role:c.role};}
  if(c.action==='method_status'){before=await one(q,'SELECT id,user_id,status FROM payout_methods WHERE id=$1 FOR UPDATE',[c.id]);if(!before)throw new DomainError('Method not found.',404);await q.query('UPDATE payout_methods SET status=$2,is_primary=false WHERE id=$1',[c.id,c.status]);after={status:c.status};userId=before.user_id;}
  if(c.action==='security_review'){await this.active(q,c.userId);const e=await one(q,"INSERT INTO security_events(user_id,event,reason) VALUES($1,'ACCOUNT_REVIEW_REQUIRED',$2) RETURNING id",[c.userId,c.reason]);target=e.id;after={status:'Open'};await q.query("UPDATE profiles SET verification_status='Review required',updated_at=now() WHERE user_id=$1",[c.userId]);await this.notify(q,c.userId,'SECURITY_ALERT');}
  if(c.action==='security_resolve'){before=await one(q,"SELECT * FROM security_events WHERE id=$1 AND status='Open' FOR UPDATE",[c.id]);if(!before)throw new DomainError('Open event not found.',404);await q.query("UPDATE security_events SET status='Resolved' WHERE id=$1",[c.id]);await q.query("UPDATE profiles SET verification_status='Not verified',updated_at=now() WHERE user_id=$1 AND NOT EXISTS(SELECT 1 FROM security_events WHERE user_id=$1 AND status='Open')",[before.user_id]);userId=before.user_id;after={status:'Resolved'};}
  if(c.action==='template'){before=await one(q,'SELECT * FROM notification_templates WHERE id=$1 FOR UPDATE',[c.id]);if(!before)throw new DomainError('Template not found.',404);await q.query('UPDATE notification_templates SET title=$2,message=$3,enabled=$4,updated_at=now() WHERE id=$1',[c.id,c.title,c.message,c.enabled]);after={title:c.title,message:c.message,enabled:c.enabled};}
  if(c.action==='notify'){await this.active(q,c.userId);const n=await one(q,'INSERT INTO notifications(user_id,title,message) VALUES($1,$2,$3) RETURNING id',[c.userId,c.title,c.message]);after={notificationId:n.id};}
  if(c.action==='payout_reveal'){const m=await one(q,'SELECT * FROM payout_methods WHERE id=$1',[c.id]);if(!m)throw new DomainError('Method not found.',404);await this.audit(q,a,'PAYOUT_DATA_ACCESSED','payout_method',m.id,c.reason,null,{purpose:'authorized_processing'});return {details:this.vault.decrypt(m.encrypted_details,m.user_id)};}
  if(c.action==='referral_settings'){before=await one(q,'SELECT * FROM referral_settings WHERE id=1 FOR UPDATE');if(before.revision!==c.revision)throw new DomainError('Referral settings changed.',409);await q.query('UPDATE referral_settings SET enabled=$1,reward_type=$2,reward_rate=$3,maximum_reward_atomic=$4,qualification_atomic=$5,revision=revision+1 WHERE id=1',[c.enabled,c.rewardType,c.rewardRate,String(centsToAtomic(c.maximumReward)),String(centsToAtomic(c.qualification))]);after={...c};}
  if(c.action==='referral_reward'){
   const referral=await one(q,'SELECT * FROM referrals WHERE id=$1 FOR UPDATE',[c.id]);if(!referral||referral.status!=='Eligible')throw new DomainError('Referral is not eligible or already rewarded.',409);const settings=referral.settings_snapshot;if(!(await one(q,'SELECT enabled FROM referral_settings WHERE id=1')).enabled)throw new DomainError('Rewards are paused.');await this.active(q,referral.referrer_id);await this.active(q,referral.referred_id);const wallet=await this.lockWallet(q,referral.referrer_id);
   const total=BigInt((await one(q,"SELECT COALESCE(sum(amount_atomic),0)::text total FROM deposit_requests WHERE user_id=$1 AND status='CONFIRMED'",[referral.referred_id])).total);if(total<BigInt(settings.qualification_atomic))throw new DomainError('Qualification threshold not met.',409);
   // Rates are stored as decimal strings and calculated in integer millionths.
   const rate=BigInt(String(settings.reward_rate).split('.')[0])*1000000n+BigInt((String(settings.reward_rate).split('.')[1]||'').padEnd(6,'0'));
   const reward=settings.reward_type==='PERCENTAGE'?total*rate/100000000n:rate;const capped=reward>BigInt(settings.maximum_reward_atomic)?BigInt(settings.maximum_reward_atomic):reward;if(capped<=0n)throw new DomainError('Reward must be positive.');
   const l=await one(q,"INSERT INTO wallet_ledger(wallet_id,amount_atomic,kind,reference,operation_id,reason,actor_id) VALUES($1,$2,'REFERRAL_REWARD',$3,$4,$5,$6) RETURNING id",[wallet.id,String(capped),referral.id,c.operationId,c.reason,a.id]);await q.query('INSERT INTO referral_rewards(referral_id,ledger_id,amount_atomic) VALUES($1,$2,$3)',[referral.id,l.id,String(capped)]);await q.query("UPDATE referrals SET status='Paid' WHERE id=$1",[referral.id]);userId=referral.referrer_id;before={status:'Eligible'};after={status:'Paid',amountAtomic:String(capped)};
  }
  await this.audit(q,a,c.action.toUpperCase(),c.action,target,c.reason,before,after);await this.event(q,userId,'account.updated',target);return {ok:true};
 });}
 async userAction(a:Actor,c:any){if(c.action==='request')return this.submit(a,c);if(c.action==='cancel')return this.resolveWithdrawal(a,{...c,decision:'cancel',reason:'Cancelled by the wallet owner'});
  return this.atomic(a,c.operationId,c,async q=>{await this.active(q,a.id);await this.lockWallet(q,a.id);
   if(c.action==='read_notifications'){await q.query('UPDATE notifications SET read_at=now() WHERE user_id=$1 AND read_at IS NULL',[a.id]);return {ok:true};}
   if(c.action==='profile')await q.query('UPDATE users SET name=$2 WHERE id=$1',[a.id,c.name]);
   else if(c.action==='method_add'){
    if(Number((await one(q,"SELECT count(*) n FROM payout_methods WHERE user_id=$1 AND status='Active'",[a.id])).n)>=6)throw new DomainError('Maximum six active payout methods.');
    const details=c.details||(this.mode==='test'?{type:'TRC20',address:'TEST-DESTINATION-'+a.id}:null);if(!details)throw new DomainError('Payout details are required.');
    const type=details.type||'TRC20';const value=type==='BANK'?details.accountNumber:type==='UPI'?details.upiId:details.address;if(typeof value!=='string'||value.length<4)throw new DomainError('Invalid payout destination.');
    await q.query('INSERT INTO payout_methods(user_id,type,name,masked_detail,encrypted_details,is_primary) VALUES($1,$2,$3,$4,$5,NOT EXISTS(SELECT 1 FROM payout_methods WHERE user_id=$1 AND is_primary AND status=\'Active\'))',[a.id,type,c.name,'••••'+value.slice(-4),this.vault.encrypt(details,a.id)]);
   }else if(c.action==='method_change'){
    const m=await one(q,"SELECT * FROM payout_methods WHERE id=$1 AND user_id=$2 AND status='Active' FOR UPDATE",[c.id,a.id]);if(!m)throw new DomainError('Method not found.',404);
    if(c.change==='remove'){if(await one(q,"SELECT id FROM withdrawal_requests WHERE payout_method_id=$1 AND status IN ('REQUESTED','UNDER_REVIEW','PROCESSING')",[c.id]))throw new DomainError('This method has an open withdrawal.');await q.query("UPDATE payout_methods SET status='Disabled',is_primary=false WHERE id=$1",[c.id]);}
    else await q.query('UPDATE payout_methods SET is_primary=(id=$2) WHERE user_id=$1',[a.id,c.id]);
   }else if(c.action==='link_referral'){
    const settings=await one(q,'SELECT * FROM referral_settings WHERE id=1');if(!settings.enabled)throw new DomainError('Referrals are paused.');const code=await one(q,'SELECT * FROM referral_codes WHERE code=$1 AND user_id<>$2',[c.code.toUpperCase(),a.id]);if(!code)throw new DomainError('Invalid referral code.');
    // New accounts must link before their first confirmed deposit.
    if(await one(q,"SELECT id FROM deposit_requests WHERE user_id=$1 AND status='CONFIRMED'",[a.id]))throw new DomainError('Link a referral before your first confirmed deposit.');
    await q.query('INSERT INTO referrals(referrer_id,referred_id,settings_snapshot) VALUES($1,$2,$3) ON CONFLICT(referred_id) DO NOTHING',[code.user_id,a.id,JSON.stringify(settings)]);
   }else if(c.action==='connect_email'){
    if(c.consent!==true)throw new DomainError('Explicit consent is required.');await q.query("INSERT INTO notification_connections(user_id,channel,encrypted_destination,consent_at) VALUES($1,'Email',$2,now()) ON CONFLICT(user_id,channel) DO UPDATE SET revoked_at=NULL,consent_at=now(),encrypted_destination=excluded.encrypted_destination",[a.id,this.vault.encrypt({email:a.email},a.id)]);
   }else if(c.action==='disconnect_notification')await q.query('UPDATE notification_connections SET revoked_at=now() WHERE user_id=$1 AND channel=$2',[a.id,c.channel]);
   else throw new DomainError('Unsupported user operation.');
   await this.audit(q,a,c.action.toUpperCase(),'user',a.id,'Requested by the wallet owner',null,{action:c.action});await this.event(q,a.id,'account.updated',a.id);return {ok:true};
  });
 }
 async adminAction(a:Actor,c:any){if(c.action==='settings')return this.settings(a,c);if(c.action==='adjust')return this.adjustment(a,c);if(c.action==='stage')return this.stage(a,c);
  if(c.action==='review'){const d=await one(this.db,'SELECT id FROM deposit_requests WHERE id=$1',[c.id]);if(d)return c.decision==='approve'?this.verifyDeposit(a,c):this.rejectDeposit(a,c);return c.decision==='approve'?this.payout(a,c):this.resolveWithdrawal(a,c);}return this.manage(a,c);
 }
 async snapshot(a:Actor,admin=false){if(admin&&(!a.role||a.aal!=='aal2'))throw new DomainError('Administrator access required.',403);const allowed=(p:string)=>!admin||a.permissions.includes(p);const scope=admin?'':' WHERE u.id=$1',args=admin?[]:[a.id];
  const userRows=(!admin||allowed('users.read'))?(await this.db.query(`SELECT u.*,p.verification_status,a.role_id role,c.code referral_code,w.id wallet_id,COALESCE((SELECT sum(amount_atomic) FROM wallet_ledger WHERE wallet_id=w.id),0)::text total,COALESCE((SELECT sum(amount_atomic) FROM wallet_holds WHERE wallet_id=w.id AND status='ACTIVE'),0)::text held FROM users u JOIN profiles p ON p.user_id=u.id JOIN wallets w ON w.user_id=u.id JOIN referral_codes c ON c.user_id=u.id LEFT JOIN admin_users a ON a.user_id=u.id AND a.enabled ${scope} ORDER BY u.created_at DESC LIMIT 500`,args)).rows:[];
  const users=userRows.map(u=>({...u,email:allowed('users.read')?u.email:'',available:allowed('finance.read')?uiUnits(BigInt(u.total)-BigInt(u.held)):0,held:allowed('finance.read')?uiUnits(u.held):0,total:undefined,wallet_id:undefined}));
  const scoped=async(table:string,columns:string,permission:string,extra='')=>allowed(permission)?(await this.db.query(`SELECT ${columns},u.name user_name FROM ${table} t JOIN users u ON u.id=t.user_id ${extra} ${admin?'':'WHERE t.user_id=$1'} ORDER BY t.created_at DESC LIMIT 500`,args)).rows:[];
  const deposits=await scoped('deposit_requests','t.*','finance.read');const withdrawals=await scoped('withdrawal_requests','t.*,p.name method','finance.read','JOIN payout_methods p ON p.id=t.payout_method_id');
  const requests=[...deposits.map(d=>({id:d.id,user_id:d.user_id,user_name:d.user_name,type:'Deposit',units:uiUnits(d.amount_atomic),fee:0,status:d.status==='CONFIRMED'?'Completed':d.status==='REJECTED'?'Rejected':'Pending',stage:d.status,method:'USDT · TRC20',reference:d.tx_hash,created_at:d.created_at,resolved_at:d.resolved_at,reason:d.reason,reviewed_by:d.reviewed_by})),...withdrawals.map(w=>({id:w.id,user_id:w.user_id,user_name:w.user_name,type:'Withdrawal',units:uiUnits(w.amount_atomic),fee:uiUnits(w.fee_atomic),status:w.status==='COMPLETED'?'Completed':w.status==='REJECTED'||w.status==='FAILED'?'Rejected':w.status==='CANCELLED'?'Cancelled':'Pending',stage:w.status,method:w.method,method_id:w.payout_method_id,payout_currency:w.payout_currency,payout_amount_paise:w.payout_amount_paise,exchange_rate_inr:w.exchange_rate_inr,source_amount_atomic:w.source_amount_atomic,created_at:w.created_at,resolved_at:w.resolved_at,reason:w.reason,reviewed_by:w.reviewed_by}))].sort((x,y)=>Date.parse(y.created_at)-Date.parse(x.created_at));
  const ledger=allowed('finance.read')?(await this.db.query(`SELECT l.*,w.user_id,u.name user_name,a.name actor_name FROM wallet_ledger l JOIN wallets w ON w.id=l.wallet_id JOIN users u ON u.id=w.user_id JOIN users a ON a.id=l.actor_id ${admin?'':'WHERE w.user_id=$1'} ORDER BY l.created_at DESC LIMIT 500`,args)).rows.map(l=>({...l,available_delta:uiUnits(l.amount_atomic),held_delta:0})):[];
  const methods=(await scoped('payout_methods','t.id,t.user_id,t.name,t.type,t.currency,t.masked_detail detail,t.status,t.is_primary,t.created_at','payouts.read')).map(m=>({...m,is_primary:m.is_primary?1:0}));
  const notifications=await scoped('notifications','t.*','notifications.read');const security=await scoped('security_events','t.*','security.read');
  const audit=admin&&allowed('audit.read')?(await this.db.query('SELECT l.*,u.name actor_name FROM audit_logs l JOIN users u ON u.id=l.admin_user_id ORDER BY l.created_at DESC LIMIT 500')).rows.map(l=>({...l,actor_id:l.admin_user_id,target_id:l.resource_id,details:JSON.stringify({previous_state:l.previous_state,new_state:l.new_state,ip_address:l.ip_address,user_agent:l.user_agent})})):[];
  const referrals=allowed('referrals.read')?(await this.db.query(`SELECT r.*,a.name referrer_name,b.name referred_name,w.amount_atomic reward_atomic,w.created_at paid_at FROM referrals r JOIN users a ON a.id=r.referrer_id JOIN users b ON b.id=r.referred_id LEFT JOIN referral_rewards w ON w.referral_id=r.id ${admin?'':'WHERE r.referrer_id=$1'} ORDER BY r.created_at DESC LIMIT 500`,args)).rows.map(r=>({...r,reward_units:uiUnits(r.reward_atomic||r.settings_snapshot.maximum_reward_atomic),minimum_units:uiUnits(r.settings_snapshot.qualification_atomic)})):[];
  const templates=admin&&allowed('notifications.read')?(await this.db.query('SELECT * FROM notification_templates ORDER BY id')).rows.map(t=>({...t,enabled:t.enabled?1:0,channel:t.channels.join(', ')})):[];
  const settings=await this.config();return {viewer:{id:a.id,name:a.name,email:a.email,role:a.role},users,requests,ledger,methods,notifications,security,audit,referrals,templates,settings:settings.value,settingsRevision:settings.revision,permissions:a.permissions,financialRedacted:!allowed('finance.read'),mode:this.mode==='test'?'test':'live'};
 }
}
